### ISSUE TITLE
updated webscrapbook, but get error saying it needs to be updated

### ISSUE THREAD

**Issue by gred22** [danny0838/PyWebScrapBook#26] opened 2020-11-03 16:56 UTC
I have updated webscrapbook and pip several times.  Today I got an error message:

Fatal error: Require server app version >= 0.29.0

So I updated webscrapbook and pip, and got the error again, ran the update for webscrapbook again, and it indicates that it is already satisfied, and that the version is 0.31.0, yet I keep getting the error message that it has to be >= 0.29.0.

How can I fix this?

thanks - Mark

**Comment by danny0838** [comment] 2020-11-03 17:33
Seems like you have the similar issue as #24..

Please report your OS. And, try below two commands and report the output:

    python -m webscrapbook --version

    wsb --version

**Comment by gred22** [comment] 2020-11-03 20:40
Here are the results - 

C:\Users\xxxxx>python -m webscrapbook --version
webscrapbook 0.31.0

C:\Users\xxxxx>wsb --version
webscrapbook 0.31.0

**Comment by danny0838** [comment] 2020-11-04 03:29
Oops, that's bezare. Your server app seems OK. Check if there's still an old running process, or reboot your device?

**Comment by gred22** [comment] 2020-11-04 19:06
Well, I had not rebooted or shut down for several days, so I closed everything and restarted.  But now I get a different error when I try to save a page - 

Error when generating fulltext cache: Malformed tree file wrapping

WTF is going on, please?  Please help - I use wsb a LOT.

thanks - Mark

**Comment by danny0838** [comment] 2020-11-05 04:08
Seems your fulltext index file(s) are corrupted due to an unknown reason (possibly due to an interruption when the server is saving).

It's rather easy for fulltext—just delete them (`<tree_dir>/fulltext#.js`, where `<tree_dir>` is the tree_dir configured in the server, and `#` may be empty or a positive number) and run the indexer again. Of course you can move/rename them instead for a backup.

The typical format of `fulltext#.js` is like:

```js
/**
 * This file is generated by WebScrapBook and is not intended to be edited.
 */
scrapbook.fulltext({...})
```

You can try to fix it by yourself, or, report here if it doesn't bother, which may do some help for further investigation.

Also check if sidebar can be opened normally, and backup `<tree_dir>/meta#.js` and `<tree_dir>/toc#.js` occasionally. There's current no automatic backup mechanism for them and their corruption may be difficult to repair and cause permanent data loss.

For further details check [data scheme](https://github.com/danny0838/webscrapbook/wiki/Scheme#index-files).

**Comment by gred22** [comment] 2020-11-05 16:57
I can open ScrapBook, and it appears all my saved pages are there.  But my D:\wsb\tree\fulltext.js file is empty, 0 bytes.  The meta.js file is 2382 KB, and the toc.js file is 146 KB.

I deleted fulltext.js and ran indexer, got an error - see (wsb gen index 2.pdf)
I moved the folder shown just before the error, and the folder after, and re-ran the indexer
This time it completed - see (wsb 2nd gen index end.pdf)
But there were multiple other errors - see (wsb 2nd gen index err1 - err6.pdf)
It also created another fulltext.js file, but again empty with 0 bytes

Should the fulltext.js file have contents?
Is there a way to correct the "local variable exc referenced before assignment"?
Is there anything I can do to correct the "no element found" errors?

thanks for your support - Mark
[wsb 2nd gen index err3.pdf](https://github.com/danny0838/PyWebScrapBook/files/5495787/wsb.2nd.gen.index.err3.pdf)
[wsb 2nd gen index err2.pdf](https://github.com/danny0838/PyWebScrapBook/files/5495788/wsb.2nd.gen.index.err2.pdf)
[wsb 2nd gen index err1.pdf](https://github.com/danny0838/PyWebScrapBook/files/5495790/wsb.2nd.gen.index.err1.pdf)
[wsb 2nd gen index end.pdf](https://github.com/danny0838/PyWebScrapBook/files/5495791/wsb.2nd.gen.index.end.pdf)
[wsb gen index 2.pdf](https://github.com/danny0838/PyWebScrapBook/files/5495792/wsb.gen.index.2.pdf)
[wsb 2nd gen index err6.pdf](https://github.com/danny0838/PyWebScrapBook/files/5495793/wsb.2nd.gen.index.err6.pdf)
[wsb 2nd gen index err5.pdf](https://github.com/danny0838/PyWebScrapBook/files/5495794/wsb.2nd.gen.index.err5.pdf)
[wsb 2nd gen index err4.pdf](https://github.com/danny0838/PyWebScrapBook/files/5495795/wsb.2nd.gen.index.err4.pdf)

**Comment by gred22** [comment] 2020-11-05 17:12
I don't understand - wsb seems to save pages, and I can access them after I open wsb, but I still get a full text cache error - see (wsb fulltext error.pdf)

thanks - Mark
[wsb still fulltext error.pdf](https://github.com/danny0838/PyWebScrapBook/files/5495879/wsb.still.fulltext.error.pdf)

**Comment by danny0838** [comment] 2020-11-05 17:31
1. Please report your OS, browser, and version of WSB.

2. We just released a small patch that should hopefully fix the `local variable 'exc' ...` error (though it's probably not the main issue). Please upgrade PyWSB to 0.32.1

3. Please delete `fulltext.js` and re-run the indexer, and paste full log text (indent with 4 spaces to escape special syntax) instead of PDFs.

4. Please provide one of the html files with `no element found` error. For example, `20200819205425327/index.html`.

**Comment by gred22** [comment] 2020-11-06 19:55
I'm not sure what happened - I posted an answer I don't see here - here goes again:
1. windows 10, browser mainly vivaldi, but also brave - both chrome based, with wsb, wsb was 0.31.0 as shared above
2. yes, updated to 0.32.1
3. deleted fulltext.js, re-ran indexer, not sure about your instructions on pasting full log, but will paste here? indent 4 spaces? I copied the log of the index into a word document - 73 pages worth - (wsb log index.docx)
5. uploading also the 20200819205425327/index.html file (but there are 16 more index.html files, as well?
6. I got here, after re-running indexer, so was not able to do this.


I tried uploading the docx and html and get an error that they don't support that file type(html?).  So I will make a zip file.

[wsb log index.zip](https://github.com/danny0838/PyWebScrapBook/files/5503202/wsb.log.index.zip)

**Comment by danny0838** [comment] 2020-11-07 03:35
@gred22 

Unfortunately I haven't found the cause of why `fulltext.js` was saved empty on your device. We still need further investigation.

>     1. windows 10, browser mainly vivaldi, but also brave - both chrome based, with wsb, wsb was 0.31.0 as shared above
I mean version of WebScrapBook browser extension, not PyWebScrapBook. And please also include browser version.

Vilvadi was known to have a bug (see https://github.com/danny0838/webscrapbook/issues/31#issuecomment-347202901). I haven't checked if it's resolved in the latest version, and Brave is also not checked.

As there may be an issue of the browser, please also try running the indexer with lastest version of Google Chrome after deleting `fulltext.js`, check if `fulltext.js` is still saved empty, and report the log.

> 
>     3. deleted fulltext.js, re-ran indexer, not sure about your instructions on pasting full log, but will paste here? indent 4 spaces? I copied the log of the index into a word document - 73 pages worth - (wsb log index.docx)

I meant you can just copy the log content and include as a text block, by indenting all lines with 4 spaces:

```
    Caching book "" (scrapbook).
    Generating fulltext cache...
    ....
    Time spent: 396.9119119644165 seconds.
```

Or, alternatively, wrap with \`\`\`:

    ```
    Caching book "" (scrapbook).
    Generating fulltext cache...
    ....
    Time spent: 396.9119119644165 seconds.
    ```

Both the above way will shown like:

```
Caching book "" (scrapbook).
Generating fulltext cache...
....
Time spent: 396.9119119644165 seconds.
```

But if you prefer to copy it in MS Word it's also OK.

> 
>     4. uploading also the 20200819205425327/index.html file (but there are 16 more index.html files, as well?

This file is normal. It seems that it's an issue that a linked frame page is malformatted, so are other pages with `no element found` issue. There's also an issue of the current PyWSB, and PyWSB 0.32.2 was released to fix it, so that only the frame in question is not indexed.

However, the page 20200819205425327 should not be be captured malformatted. I tried capturing the same source page https://www.ebay.com/itm/New-Velvet-Jewelry-Store-Style-XL-Necklace-Pearl-Red-Heart-Gift-Box/332365839058?hash=item4d628c3ad2:g:J1EAAMXQV0BSLjfM on Google Chrome 86.0.4240.183 and didn't see the issue.

Please delete `fulltext.js`, disable all extensions except for WebScrapBook, and try capturing the same page with the latest version of Vilvadi, Brave, and Google Chrome, respectively, and report the logs in the capture dialog.

**Comment by gred22** [comment] 2020-11-07 19:19
WebScrapBook = 0.91.0
Vivaldi = 3.4.2066.86
Brave = 1.16.72
Chrome = 86.0.4240.183
As for a bug in Vivaldi or Brave, I have used both to save dozens and dozens of pages, wtih not problems, until this episode we are working on now.

Deleted fulltext.js (77016 KB)
Tried to run indexer from chrome, kept getting “Unable to connect to backend server.” Error
I have all options in chrome set the same as in Vivaldi and Brave, I initialized the server with chrome as the default browser, but I cannot get past this error.

**Comment by danny0838** [comment] 2020-11-08 02:47
fulltext.js with 77MB is obviously not empty and is probably normal... How did you get it? Had you confirmed that it didn't work before deleting it? Anyway, you probably have done right for at least once...

I don't think Google Chrome cannot work. Did you forget to start the server? Did you tried Vivaldi and Brave after getting “Unable to connect to backend server.” error for GC? How did you confirm options of GC are actually identical with Vivaldi and Brave? Have you exported options from them and imported to GC? ... etc.

Your issue cannot be reproduced. It really seems to be caused by some trivial operation errors you have made. Please be more clear about what you have actually done, or I really cannot help you.

And, as mentioned before:

> Please upgrade PyWSB to 0.32.2, delete fulltext.js, disable all extensions except for WebScrapBook, try capturing the same page, check if fulltext.js is saved empty, and report the logs in the capture dialog, using the latest version of Vilvadi, Brave, and Google Chrome, respectively.

If you still cannot get it work for GC anyway, please at least do the test for Vivaldi and Brave and provide their logs.

**Comment by gred22** [comment] 2020-11-08 22:42
I'm sorry, I cannot at this time dedicate this much time to this.  I am 67, I am trying to get at least 3 different books published early next year.  I loved scrapbook, and scrapbookx because they were the only manner I could find to save complete web pages accurately.  And I had hope of consolidating decades and many gigabytes of scrapbook/x data into a common database with wsb.  I appreciate all the hard work you have done.  But, it has been very inconvenient to not be able to make and specify folders to save a page with wsb, like I could with scrapbookx.  I just repeated a bunch of these macinations, and the first page saved fine, then the next two had errors and did not save.  I do not have time to play with and do tests on chrome when I do not use it to save pages.  Thank you for all your prompt assistance, but  am going to explore other options, including evernote (which way back when would not accurately save a web page, but now decades later maybe has resolved/improved it) and just printing pages into pdfs, to maybe then store in evernote - using Print Friendly which is great.  Anyway, thanks for all your help, maybe I'll come back next year when I don't have so many deadlines.

**Comment by danny0838** [comment] 2020-11-11 03:43
Currently we cannot easily reproduce your problem, so we really need further details for investigation.

You can choose whatever tool you are comfortable with. If WSB currently doesn't work well for you, using legacy ScrapBook (X) is also a way to go. Legacy ScrapBook (X) collections can be merged into WSB in the future by converting legacy scrapbook(s) into WebScrapBook scrapbook(s) and transferring items between scrapbooks.

**Comment by gred22** [comment] 2020-11-15 15:33
Yes, I continued with Scrapbook X for a long long time.  But, with it, I cannot update firefox beyond 56.0.2 I think it is.  And with that version of firefox - many sites will not play their videos or present forms to fill correctly, etc.

**Comment by danny0838** [comment] 2020-11-15 15:37
Yes, that's the side of using old Firefox. There are sill Firefox forks like Waterfox and Pale Moon, AFAIK. Though they may still have their own issues. That's why we have been working to make WSB a good replacement of SBX.

**Closed** 2021-03-19 10:12 UTC
Labels: question
